CollActionteam/CollAction

src/CollAction/Controllers/ProjectsController.cs, src/CollAction/Models/Project.cs, src/CollAction/Models/ProjectStatus.cs, src/CollAction/Models/ProjectViewModels/BrowseProjectsViewModel.cs, src/CollAction/Models/ProjectViewModels/CreateProjectViewModel.cs, src/CollAction/Models/ProjectViewModels/DisplayProjectViewModel.cs, src/CollAction/Models/ProjectViewModels/EditProjectViewModel.cs, src/CollAction/Models/ProjectViewModels/FindProjectsViewModel.cs, src/CollAction/Views/Projects/Create.cshtml, src/CollAction/Views/Projects/Delete.cshtml, src/CollAction/Views/Projects/Details.cshtml, src/CollAction/Views/Projects/Edit.cshtml, src/CollAction/Views/Projects/Find.cshtml, src/CollAction/Views/Projects/Index.cshtml
CA-80 StartProjectViewModel, CA-82 DisplayProjectViewModel, CA-84 BrowseProjectsViewModel
- The Create Project Action actually uses the new EditProjectViewModel (as does the Edit Project Action).
- Added validation when user attempts to create a project of the same name.
- Made changes to ProjectsController to calculate the participation counts (needed for 'Progress' field)
- Added 'RemainingDays' and 'StatusDescription' properties to the Project model.
=> CA-80, CA-82, CA-84

src/CollAction/Data/ApplicationDbContext.cs, src/CollAction/Migrations/20170202065355_ImageFile.Designer.cs, src/CollAction/Migrations/20170202065355_ImageFile.cs, src/CollAction/Models/ImageFile.cs
- The resolution is stored in two fields width and height
=> CA161 Table ImageFile

src/CollAction/Controllers/ProjectsController.cs, src/CollAction/Views/Projects/Details.cshtml
- also removed the edit link from the details page
=> CA_184 Fixed "logged off users cannot view the find or index page" bug

CollAction/Controllers/AdminController.cs, CollAction/Controllers/ProjectsController.cs, CollAction/Helpers/ImageFileManager.cs, CollAction/Helpers/TimeSpanExtensions.cs, CollAction/Models/AdminViewModels/ManageProjectViewModel.cs, CollAction/Models/Project.cs, CollAction/Models/ProjectViewModels/CreateProjectViewModel.cs, CollAction/Models/ProjectViewModels/DisplayProjectViewModel.cs, CollAction/Models/ProjectViewModels/EditProjectViewModel.cs, CollAction/Views/Admin/ManageProject.cshtml, CollAction/Views/Projects/Details.cshtml, CollAction/Views/Projects/ThankYouCreate.cshtml, docker-compose.dcproj
This fixes a lot for the project flow. CA-217, CA-224 and the message ron entered in his document. Also fixes project tagging issues during creation (missed that issue, small).
=> Project details (CA-217) + Management page fixes (CA-224) + correct e-mail and thank you messages

CollAction/Controllers/AdminController.cs, CollAction/Models/Project.cs
And some small code formatting issues I happened to notice
=> Fix management of projects without video link

CollAction/Dockerfile, CollAction/Helpers/ImageFileManager.cs, docker-compose.yml
External image hosting + a small fix.
=> external-images

CollAction/Startup.cs, CollAction/ValidationAttributes/WithinMonthsAfterTodayAttribute.cs, CollAction/Views/Shared/_Footer.cshtml
=> Small tweaks

CollAction/Controllers/AccountController.cs, CollAction/Controllers/ManageController.cs, CollAction/Dockerfile, CollAction/Helpers/ImageFileManager.cs, CollAction/Helpers/MailChimpManager.cs, CollAction/Models/AdminViewModels/ManageProjectViewModel.cs, docker-compose.yml
Fix the volume mapping of the user content, also:
* Makes mailchimp registration a bit more robust
* Removes the startdate validation from the admin screen, so the admin has the freedom to start a project immediately
=> fix volume

CollAction/Services/MessageServices.cs
Logging for sendgrid failures, so we can diagnose the email issue.
=> Log sendgrid failure

CollAction/Views/Projects/Commit.cshtml
- Changed the commit page text to read [Click "I participate" to join the project!].
=> CA-263_I_Participate

CollAction/Controllers/AdminController.cs, CollAction/Services/IProjectService.cs, CollAction/Services/ProjectService.cs, CollAction/Views/Admin/ManageProject.cshtml
Given that this is suddenly necessary, an export of the participants data.
=> CA-70 - Participants data export

CollAction/Views/Shared/_Footer.cshtml
- Button now loads the CollAction facebook page rather than sharing CollActions.
=> FacebookButtonInFooter_CA_252

CollAction/Controllers/ProjectsController.cs, CollAction/Services/MessageServices.cs
* Log SES errors properly
* fix html e-mails
* Fix error project e-mails
=> Numerous e-mail fixes

build.ps1, build.sh
Stewart added a production mode to the minimize step. This adds that to the build script.
=> Build the javascript minimizer in production mode in the build scripts

CollAction/Frontend/app/index.ts, CollAction/Views/Shared/_Layout.cshtml
=> ca-284 Hide body and show after loading is finished

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs, CollAction/Migrations/20170730084318_CA_256_change_category_names.Designer.cs, CollAction/Migrations/20170730084318_CA_256_change_category_names.cs
-  Added a migration script and changed the category seed function to change category Consuming to Consumption and Wellbeing to Well-being.
- Ordered the categories alphabetically in the search select box.
=> CA-256-change-category-names

CollAction/Frontend/app/home/styles/about.scss, CollAction/Views/Home/About.cshtml, CollAction/Views/Shared/_Footer.cshtml
- Got all the links working appropriately bar one (the 'press' link doesn't have a corresponding press section in the about page).
- Also added a small javascript to the about page in order to fix the navigation bar offsetting the page incorrectly when navigating via a link to a page fragment.
=> CA-274-FooterLinksDoNotWorkFix

CollAction.Tests/MailChimpManagerTests.cs
- This has Mina's contact details change in it. It's been tested on an AWS test stack.
- Also has a change to the package.json required to let my docker build work.
- The mailchimp newsletter subscriptions work too. It has been tested on the AWS stack. Were some misconfiguration issues in the env_collaction variables.
=> Mail chimp error

CollAction/CollAction.csproj, CollAction/Views/Home/About.cshtml
Changes are on my testserver. Maybe stewart can test them w/ cloud formation later (haven't figured that out yet).
=> Youtube https fix + build errors related to team photos

CollAction/Controllers/ProjectsController.cs, CollAction/Frontend/app/project/ProjectFilter.tsx
- Took out the text "Filter Projects By" when displaying on extra small screens (mobile devices).
- Changed the filter text "All Projects" to "All" to better match the surrounding text.
=> CA-294-filter-text-changes:

CollAction/Frontend/app/admin/styles/ManageProject.scss, CollAction/Frontend/app/project/styles/ProjectCreate.scss, CollAction/Models/AdminViewModels/ManageProjectViewModel.cs, CollAction/Models/ProjectViewModels/CreateProjectViewModel.cs, CollAction/Views/Admin/ManageProject.cshtml, CollAction/Views/Projects/Create.cshtml
- Changed inputs to textareas for properties that can have multiple lines of input.
- Gave reasonable number of initial rows (of display height) roughly based of the max character limit for each particular property.
=> CA-335-increase-text-box-areas-in-start-project

CollAction/Frontend/app/account/style.scss, CollAction/Frontend/app/account/styles/forgotPassword.scss, CollAction/Frontend/app/account/styles/forgotPasswordConfirmation.scss, CollAction/Frontend/app/account/styles/resetPassword.scss, CollAction/Frontend/app/account/styles/resetPasswordConfirmation.scss, CollAction/Frontend/app/global/styles/header.scss, CollAction/Frontend/app/project/styles/FindProject.scss, CollAction/Views/Account/ForgotPassword.cshtml, CollAction/Views/Account/ForgotPasswordConfirmation.cshtml, CollAction/Views/Account/ResetPassword.cshtml, CollAction/Views/Account/ResetPasswordConfirmation.cshtml
- Styled ForgotPassword, ForgotPasswordConfirmation, ResetPassword and ResetPasswordConfirmation pages.
=> CA-242-password-recovery-pages-styling

CollAction/Views/Home/About.cshtml, CollAction/Views/Shared/_Logo.cshtml, CollAction/webpack.config.js
- Fixed issue of javascript object Promise not being found on any version of IE by adding bluebird's Promise polyfill.
- Fixed tag mismatches in the About.cshtml
- Removed unnecessary </img> end tag that was throwing warnings in IE.
=> CA-336-IE-compatibility:

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs
Set Category=Friesland for all new Friesland projects
=> Ca 361 friesland startproject form

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs
=> Ca 343 add new category friesland

CollAction/Controllers/ProjectsController.cs, CollAction/Frontend/app/global/index.ts, CollAction/Frontend/app/global/styles/embed.scss, CollAction/Frontend/app/project/styles/FindProject.scss, CollAction/Views/Projects/Embed.cshtml, CollAction/Views/Shared/_EmbeddedLayout.cshtml
A first setup for embedding the project tiles into other sites (using an iframe). 
I wrote some instructions on [https://collaction.atlassian.net/wiki/spaces/CATS/pages/313753601/Embed+Projects+page+on+other+sites]
Note: it still needs to be integrated with the branch that only displays friesland-projects.
=> Ca 344 embed projects

CollAction/Frontend/app/colors.scss, CollAction/Frontend/app/global/ShareButtons.tsx, CollAction/Frontend/app/global/styles/share-buttons.scss, CollAction/Frontend/app/project/PieChart.ts, CollAction/Frontend/app/project/styles/ProjectDetails.scss, CollAction/Models/ProjectViewModels/DisplayProjectViewModel.cs, CollAction/Views/Projects/Details.cshtml
Change the category label to blue: #0168b3
Change the Project title label to blue: #0168b3
The diagram starts of with a fill of a lighter shade of red: #f29297
The diagram fill is colored to red: #e20612
Change text labels to Dutch
Quote text turned into blue
Change button to blue
Social media share box: change heading to blue
=> Ca 349 friesland project page

CollAction/Controllers/AccountController.cs, CollAction/Controllers/AdminController.cs, CollAction/Data/ApplicationDbContext.cs, CollAction/Data/DesignTimeDbContextFactory.cs, CollAction/Frontend/app/admin/index.tsx, CollAction/Frontend/app/admin/styles/ManageUser.scss, CollAction/Migrations/20180215005211_ca-365.Designer.cs, CollAction/Migrations/20180215005211_ca-365.cs, CollAction/Models/AdminViewModels/ManageUserViewModel.cs, CollAction/Models/AdminViewModels/ManageUsersIndexViewModel.cs, CollAction/Models/ApplicationUser.cs, CollAction/Services/ProjectService.cs, CollAction/Views/Admin/Index.cshtml, CollAction/Views/Admin/ManageUser.cshtml, CollAction/Views/Admin/ManageUsersIndex.cshtml
You now can have multiple participants for each users, handy if schools participate for example. This can be set by the admin.
The layout is a bit rough, but since it's an admin page, it's ok.
First this'll merge to master, then a PR that will merge this to friesland.
=> CA-365 - Multiple participants per user

CollAction/Views/Home/FAQ.cshtml
=> fixing typo in faq projets -> projects

CollAction/CollAction.csproj, CollAction/Controllers/AdminController.cs, CollAction/Controllers/ProjectsController.cs, CollAction/Frontend/app/admin/styles/ManageProject.scss, CollAction/Frontend/app/global/RichTextEditor.tsx, CollAction/Frontend/app/global/index.ts, CollAction/Frontend/app/global/styles/quill-snow.css, CollAction/Frontend/app/home/style.scss, CollAction/Frontend/app/home/styles/quill.scss, CollAction/Frontend/app/index.ts, CollAction/Frontend/app/project/FindProject.tsx, CollAction/Frontend/app/project/styles/ProjectCreate.scss, CollAction/Frontend/app/project/styles/ProjectDetails.scss, CollAction/Helpers/HtmlInputSanitizer.cs, CollAction/Migrations/20180415160636_RichTextEditing.Designer.cs, CollAction/Migrations/20180415160636_RichTextEditing.cs, CollAction/Models/AdminViewModels/ManageProjectViewModel.cs, CollAction/Models/Project.cs, CollAction/Models/ProjectViewModels/CreateProjectViewModel.cs, CollAction/ValidationAttributes/SecureRichTextAttribute.cs, CollAction/Views/Admin/ManageProject.cshtml, CollAction/Views/Projects/Create.cshtml, CollAction/Views/Projects/Details.cshtml, CollAction/package-lock.json, CollAction/package.json, CollAction/webpack.config.js
Merged branch CA-276 (rich text editing into Friesland branch).
=> Rich text editing on Friesland branch

.travis.yml, deploy.ps1, deploy.sh, scripts/docker-push.sh
Make travis build a docker container and push it to ECR. 
Add script to deploy container to ECS
=> Build Friesland docker containers through Travis, deploy with script

CollAction/Frontend/app/global/CookieMessage.tsx, CollAction/Frontend/app/global/index.ts, CollAction/Frontend/app/global/styles/cookiemessage.scss, CollAction/Frontend/app/home/styles/about.scss, CollAction/Frontend/app/home/styles/crowdactingfestival.scss, CollAction/Startup.cs, CollAction/Views/Account/Login.cshtml, CollAction/Views/Home/About.cshtml, CollAction/Views/Home/CrowdActingFestival.cshtml, CollAction/Views/Home/Index.cshtml, CollAction/Views/Projects/Details.cshtml, CollAction/Views/Projects/ThankYouCommit.cshtml, CollAction/Views/Shared/_CookieConsentPartial.cshtml, CollAction/Views/Shared/_Layout.cshtml, CollAction/package-lock.json
Show cookie message banner on every page, until the 'Accept' button has been clicked. Acceptance state is stored in a cookie on the domain the site is running on.
=> CA-401 Cookie Policy

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs, CollAction/Migrations/20180811131242_ParticipantCountMaterializedView.Designer.cs, CollAction/Migrations/20180811131242_ParticipantCountMaterializedView.cs, CollAction/Models/Project.cs, CollAction/Models/ProjectParticipantCount.cs, CollAction/Services/IProjectService.cs, CollAction/Services/ProjectService.cs
…ient queries without huge aggregates
=> CA-502 - Cache participant counts in materialized view for more efficient queries on project without huge aggregates

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs, CollAction/Migrations/20180811131242_ParticipantCountMaterializedView.Designer.cs, CollAction/Migrations/20180811131242_ParticipantCountMaterializedView.cs, CollAction/Models/Project.cs, CollAction/Models/ProjectParticipantCount.cs, CollAction/Services/IProjectService.cs, CollAction/Services/ProjectService.cs
…ient queries without huge aggregates
=> CA-503 - Cache participant counts in materialized view for more efficient queries on project without huge aggregates

CollAction/Views/Home/Privacy.cshtml
Update with translated dutch version of the policy document
=> CA-413 Friesland: Update privacy policy in Dutch

CollAction.Tests/CollAction.Tests.csproj, CollAction/CollAction.csproj, CollAction/Dockerfile, CollAction/package-lock.json, CollAction/package.json
=> CA-549 Upgrade dependencies to fix mem/cpu leak

CollAction/Views/Account/Login.cshtml
collaction.org: Add generic text to (social) login page warning on embedded user agent error
=> CA-479 Add generic text to (social) login page warning on embedded user agent

CollAction/Frontend/app/global/styles/banner.scss, CollAction/Frontend/app/project/UploadBanner.tsx, CollAction/Frontend/app/project/UploadDescriptiveImage.tsx, CollAction/Frontend/app/project/UploadImage.tsx, CollAction/Frontend/app/project/styles/ProjectCreate.scss, CollAction/Frontend/app/project/styles/ProjectDetails.scss, CollAction/Views/Projects/Create.cshtml, CollAction/package-lock.json, CollAction/package.json
Fixed a small styling issue.
And notices the image upload component didn't work anymore, most likely due to an update of react. I upgraded the react-dropzone component that it uses, after which it works again.
=> CA-590 fix banner image

CollAction/Models/ProjectViewModels/CommitProjectViewModel.cs
Hi Dominik, since you are the one that restructured the URL, can you review this little bugfix?
=> CA-585 Fixed share URL

CollAction/Controllers/ProjectsController.cs, CollAction/Frontend/app/global/Faqs.tsx, CollAction/Frontend/app/project/styles/StartInfo.scss, CollAction/Views/Home/FAQ.cshtml, CollAction/Views/Projects/StartInfo.cshtml
Added it to:
- Start project page (green card and FAQ)
- About page FAQ
- Create project confirmation email
=> Added link to project starter book (Google Docs)

CollAction/Frontend/app/project/ProjectList.tsx, CollAction/Frontend/app/project/styles/FindProject.scss, CollAction/Models/ProjectViewModels/FindProjectsViewModel.cs, CollAction/Services/Project/ProjectService.cs, CollAction/Views/Manage/Index.cshtml
I missed the 'Send e-mail to project participants' function when refactoring the accounts page; I added it back in:
=> Ca 626 mail to participants

CollAction/Frontend/app/donation/DonationBox.tsx
A few text changes as requested by Ron.
I accidentally branched from CA-321, so I added that as target branch so only the relevant changes are visible.
=> CA-678 Text changes in donation page

CollAction/Frontend/app/global/styles/footer.scss, CollAction/Frontend/app/mixins.scss, CollAction/Views/Shared/_Footer.cshtml
I re-enabled the footer mail form submit button that was previously hidden. Also added a subtle button hover effect to buttons in general.
=> Show footer email submit button

CollAction/Frontend/app/global/styles/footer.scss, CollAction/Frontend/app/mixins.scss, CollAction/Views/Shared/_Footer.cshtml
This reverts commit 38242366c3bece58301a807a56e0e6bad99b6a3f.
=> Revert "Show footer email submit button (#349)"

CollAction/Frontend/app/project/Participate.tsx
- Remove the collapsible
- Changed text
=> Ca 685 tuning participate

CollAction/Frontend/app/global/CookieMessage.tsx, CollAction/Views/Home/Privacy.cshtml
* CA-676 - update to privacy policy
* CA-650 - fix link to privacy policy
=> CA-676 & CA-650

CollAction/Controllers/ProjectsController.cs, CollAction/Data/ApplicationDbContext.cs, CollAction/Frontend/app/account/MyProjects.tsx, CollAction/Frontend/app/account/ParticipatingInProjects.tsx, CollAction/Frontend/app/global/styles/body.scss, CollAction/Frontend/app/project/FindProject.tsx, CollAction/Frontend/app/project/ProjectList.tsx, CollAction/Frontend/app/project/ProjectThumb.tsx, CollAction/Startup.cs, CollAction/Views/Projects/Embed.cshtml, CollAction/Views/Shared/_EmbeddedLayout.cshtml, CollAction/package-lock.json
Quick and dirty port of the friesland solution, given we're replacing everything, this should be fine.
=> CA-746 - embeddable project widget

CollAction/Frontend/app/index.ts, CollAction/Frontend/app/polyfills.ts, CollAction/Views/Shared/_EmbeddedLayout.cshtml, CollAction/Views/Shared/_Layout.cshtml, CollAction/package-lock.json, CollAction/webpack.config.js
Load the polyfills before the rest of the site.
=> CA-748 - Split polyfills from frontend bundle and load first

Frontend/src/assets/svg/time-to-act-act.svg, Frontend/src/assets/svg/time-to-act-crowd.svg, Frontend/src/assets/svg/time-to-act-idea.svg, Frontend/src/components/Alert/Alert.module.scss, Frontend/src/components/Button/Button.module.scss, Frontend/src/components/CallToAction/CallToAction.module.scss, Frontend/src/components/Carousel/Carousel.module.scss, Frontend/src/components/CategoryTags/CategoryTags.module.scss, Frontend/src/components/Footer/Footer.module.scss, Frontend/src/components/Layout/style.scss, Frontend/src/components/Navigation/Navigation.module.scss, Frontend/src/components/NewsletterSignup/NewsletterSignup.module.scss, Frontend/src/components/ProjectCard/ProjectCard.module.scss, Frontend/src/components/ProjectStarter/ProjectStarter.module.scss, Frontend/src/components/Section/Section.module.scss, Frontend/src/components/SocialMedia/SocialMedia.module.scss, Frontend/src/components/TimeToAct/TimeToAct.module.scss, Frontend/src/components/TimeToAct/TimeToAct.tsx, Frontend/src/pages/Home/Home.tsx, Frontend/src/pages/account/Login/Login.module.scss, Frontend/src/pages/projects/Detail/ProjectDetails.module.scss, Frontend/src/pages/projects/Find/Find.module.scss, Frontend/src/pages/projects/Start/IntroCard.module.scss, Frontend/src/pages/projects/Start/Start.module.scss, Frontend/src/translations/en/common.json
- Aligned the time to act section with the graphic design.
- Added variables according to the style guide (typography and spacing).
Can be viewed here - https://05f660f9.ngrok.io/ or https://ca-814--collaction.netlify.app/
Desktop -
Mobile -
=> CA-814 - Homepage - Time To Act Section (Static)

Terraform/common/alb.collaction.tf, Terraform/modules/database/input.tf, Terraform/modules/database/rds.tf, Terraform/production/rds.tf, Terraform/production/vars.tf, Terraform/staging/rds.tf, Terraform/test/vars.tf
Enable performance insights to rds
Add bloom office security group
=> Add backup retention period to rds

Terraform/staging/redirect-bigfoodswitch.tf, Terraform/staging/redirect-slowfashionseason.tf
These files were moved to the common section since they are part of the load balancer.
=> Moved to common infrastructure

CollAction/Services/Crowdactions/CrowdactionService.cs, CollAction/Services/Crowdactions/ICrowdactionService.cs, CollAction/Services/Initialization/InitializationService.cs, CollAction/Services/SeedOptions.cs, README.md
Speed up seeding so testselect deployment is faster
=> CA-862 - speed up seeding for testselect + minor cleanup
